---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/pacho-rh/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-konflux-ui-status-page-link
